import type { Metadata } from "next";
import Homepage from "./home-page";

export const metadata: Metadata = {
  title: "Music App",
  description: "Generated by create next app",
};

export default function RootLayout() {
  return (
    <Homepage />
  );
}
