"use client";
import React, { useState } from "react";
import {
    PlayCircle,
    Shuffle,
    Clock,
    Music,
    Loader2,
    Download,
    Share,
    Copy,
    Mail,
    MessageCircle,
    X,
} from "lucide-react";
import { useRouter } from "next/navigation";
import type { PlaylistTrack, GeneratedPlaylist } from "@/lib/types";
import { useToast } from "./ToastNotifications";

const PlaylistGenerator: React.FC = () => {
    const [prompt, setPrompt] = useState("");
    const [playlist, setPlaylist] = useState<GeneratedPlaylist | null>(null);
    const [showShareModal, setShowShareModal] = useState(false);
    const [loading, setLoading] = useState(false);
    const [error, setError] = useState("");
    const router = useRouter();
    const { addToast } = useToast();

    const generatePlaylist = async () => {
        if (!prompt.trim()) {
            setError("Please describe what kind of playlist you want");
            return;
        }

        setLoading(true);
        setError("");

        try {
            const response = await fetch("/api/ai/playlist-generate", {
                method: "POST",
                headers: { "Content-Type": "application/json" },
                body: JSON.stringify({ prompt }),
            });

            if (!response.ok) {
                const errorData = await response.json();
                throw new Error(
                    errorData.error || "Failed to generate playlist"
                );
            }

            const data = await response.json();
            setPlaylist(data.playlist);
        } catch (err) {
            setError(
                err instanceof Error
                    ? err.message
                    : "Failed to generate playlist"
            );
        } finally {
            setLoading(false);
        }
    };

    const handleTrackClick = (track: PlaylistTrack) => {
        const artistSlug = track.artist.toLowerCase().replace(/\s+/g, "-");
        router.push(`/artist/${artistSlug}`);
    };

    const exportPlaylist = () => {
        if (!playlist) return;

        const playlistText = `${playlist.name}\n${
            playlist.description
        }\n\nTracks:\n${playlist.tracks
            .map(
                (track, i) =>
                    `${i + 1}. ${track.artist} - ${track.song} (${track.album})`
            )
            .join("\n")}`;

        const blob = new Blob([playlistText], { type: "text/plain " });
        const url = URL.createObjectURL(blob);
        const a = document.createElement("a");
        a.href = url;
        a.download = `${playlist.name}.txt`;
        a.click();
        URL.revokeObjectURL(url);
    };

    const handleShare = async () => {
        if (!playlist) return;

        const shareUrl = `${window.location.origin}/playlist/${btoa(
            playlist.name
        )}`; // Simple URL encoding
        const shareData = {
            title: `🎵 ${playlist.name}`,
            text: `${playlist.description}\n\nFeaturing ${
                playlist.tracks.length
            } tracks including ${playlist.tracks
                .slice(0, 2)
                .map((t) => `${t.artist} - ${t.song}`)
                .join(" and ")}.`,
            url: shareUrl,
        };

        // Check if Web Share API is supported and can share this data
        if (navigator.share && navigator.canShare?.(shareData)) {
            try {
                await navigator.share(shareData);
                addToast({
                    type: "success",
                    message: "Playlist shared successfully!",
                });
            } catch (error: any) {
                if (error.name !== "AbortError") {
                    console.error("Share failed:", error);
                    setShowShareModal(true);
                }
            }
        } else {
            setShowShareModal(true);
        }
    };

    const copyToClipboard = async () => {
        const shareText = `🎵 ${playlist?.name}\n\n${
            playlist?.description
        }\n\nTracks:\n${playlist?.tracks
            .map(
                (track, i) =>
                    `${i + 1}. ${track.artist} - ${track.song} (${
                        track.duration
                    })`
            )
            .join("\n")}\n\nGenerated by AI Music Discovery App`;

        try {
            await navigator.clipboard.writeText(shareText);
            addToast({
                type: "success",
                message: "Playlist copied to clipboard!",
            });
            setShowShareModal(false);
        } catch (error) {
            const textArea = document.createElement("textarea");
            textArea.value = shareText;
            document.body.appendChild(textArea);
            textArea.select();
            document.execCommand("copy");
            document.body.removeChild(textArea);

            addToast({
                type: "success",
                message: "Playlist copied to clipboard",
            });
            setShowShareModal(false);
        }
    };

    const shareViaEmail = () => {
        const subject = encodeURIComponent(
            `Check out this playlist: ${playlist?.name}`
        );
        const body = encodeURIComponent(
            `Hi!\n\nI created this awesome playlist and thought you'd enjoy it:\n\n` +
                `"${playlist?.name}"\n${playlist?.description}\n\n` +
                `Tracks (${playlist?.totalDuration}):\n${playlist?.tracks
                    .map(
                        (track, i) =>
                            `${i + 1}. ${track.artist} - ${track.song} (${
                                track.duration
                            })`
                    )
                    .join("\n")}\n\n` +
                `Generated using AI Music Discovery App`
        );

        window.open(`mailto:?subject=${subject}&body=${body}`, "_blank");
        setShowShareModal(false);
    };

    const shareViaWhatsApp = () => {
        const text = encodeURIComponent(
            `🎵 Check out this playlist I created!\n\n"${playlist?.name}"\n${
                playlist?.description
            }\n\nFeaturing ${playlist?.tracks.length} tracks by ${[
                ...new Set(playlist?.tracks.map((t) => t.artist)),
            ]
                .slice(0, 3)
                .join(", ")} and more!`
        );
        window.open(`https://wa.me/?text=${text}`, "_blank");
        setShowShareModal(false);
    };

    const shareViaTwitter = () => {
        const text = encodeURIComponent(
            `🎵 Just generated this amazing playlist: "${
                playlist?.name
            }" - ${playlist?.description.substring(
                0,
                80
            )}... #AIMusic #Playlist`
        );

        window.open(`https://twitter.com/intent/tweet?text=${text}`, "_blank");
        setShowShareModal(false);
    };

    const presetPrompts = [
        "Road trip playlist with upbeat rock and indie songs",
        "Chill study session with ambient and lo-fi tracks",
        "Workout motivation with high-energy electronic music",
        "Romantic dinner with acoustic songs",
        "90s nostalgia playlist with hits from that decade",
        "Rainy day melancholy with indie folk and alternative",
    ];

    return (
        <div className="bg-[var(--surface-dark)] rounded-lg shadow-lg p-6">
            <div className="flex items-center gap-2 mb-6">
                <PlayCircle className="w-6 h-6 text-[var(--primary-500)]" />
                <h2 className="text-2xl font-bold text-white">
                    AI Playlist Generator
                </h2>
            </div>

            <div className="space-y-4">
                {/* Prompt Input */}
                <div>
                    <label className="block text-sm font-medium text-gray-200 mb-2">
                        Describe your playlist
                    </label>
                    <textarea
                        value={prompt}
                        onChange={(e) => setPrompt(e.target.value)}
                        placeholder="E.g., 'Create a workout playlist with high-energy electronic music and motivational lyrics'"
                        className="w-full p-3 border border-[var(--primary-500)] rounded-lg focus:ring-2 focus:ring-[var(--primary-500)] focus:border-transparent resize-none text-white bg-gray-800 caret-[var(--primary-500)]"
                        rows={3}
                        suppressHydrationWarning
                    />
                </div>

                {/* Preset Prompts */}
                <div>
                    <p className="text-sm text-gray-300 mb-2">
                        Or try one of these:
                    </p>
                    <div className="grid grid-cols-1 md:grid-cols-2 gap-2">
                        {presetPrompts.map((preset, index) => (
                            <button
                                key={index}
                                onClick={() => setPrompt(preset)}
                                className="text-left p-2 text-sm border border-gray-600 rounded hover:border-[var(--primary-500)] text-gray-300 hover:text-white transition-colors cursor-pointer"
                            >
                                {preset}
                            </button>
                        ))}
                    </div>
                </div>

                {/* Generate Button */}
                <button
                    onClick={generatePlaylist}
                    disabled={loading || !prompt.trim()}
                    className="w-full bg-[var(--primary-500)] text-white px-4 py-3 rounded-lg hover:bg-[var(--primary-700)] disabled:opacity-70 disabled:cursor-not-allowed flex items-center justify-center gap-2 transition-colors font-medium"
                >
                    {loading ? (
                        <>
                            <Loader2 className="w-5 h-5 animate-spin" />
                        </>
                    ) : (
                        <>
                            <Shuffle className="w-5 h-5" />
                            Generate Playlist
                        </>
                    )}
                </button>

                {error && (
                    <div className="text-red-600 text-sm p-3 bg-red-50 rounded-lg border border-red-200">
                        {error}
                    </div>
                )}

                {/* Generated Playlist */}
                {playlist && (
                    <div className="mt-8 space-y-6">
                        {/* Playlist Header */}
                        <div className="bg-gradient-to-r from-[var(--primary-500)] to-[var(--primary-700)] rounded-lg p-6 text-white">
                            <div className="flex flex-col md:flex-row items-center justify-between">
                                <div>
                                    <h3 className="text-2xl font-bold mb-2">
                                        {playlist.name}
                                    </h3>
                                    <p className="text-white/90 mb-2">
                                        {playlist.description}
                                    </p>
                                    <div className="flex items-center gap-4 text-sm text-white/80">
                                        <span className="flex items-center gap-1">
                                            <Music className="w-4 h-4" />
                                            {playlist.tracks.length} tracks
                                        </span>
                                        <span className="flex items-center gap-1">
                                            <Clock className="w-4 h-4" />
                                            {playlist.totalDuration}
                                        </span>
                                        <span className="bg-white/20 px-2 py-1 rounded">
                                            {playlist.theme}
                                        </span>
                                    </div>
                                </div>
                                <div className="flex gap-2">
                                    <button
                                        onClick={exportPlaylist}
                                        className="bg-white/20 hover:bg-white/30 p-2 rounded-lg transition-colors group"
                                        title="Export playlist"
                                    >
                                        <Download className="w-5 h-5 group-hover:scale-110 transition-transform" />
                                    </button>
                                    <button
                                        onClick={handleShare}
                                        className="bg-white/20 hover:bg-white/30 p-2 rounded-lg transition-colors group"
                                        title="Share playlist"
                                    >
                                        <Share className="w-5 h-5 group-hover:scale-110 transition-transform" />
                                    </button>
                                </div>
                            </div>
                        </div>

                        {/* Track List */}
                        <div className="space-y-2">
                            <h4 className="font-semibold text-white mb-3">
                                Tracks:
                            </h4>
                            {playlist.tracks.map((track, index) => (
                                <div
                                    key={index}
                                    className="flex items-center justify-between p-4 bg-gray-800 rounded-lg hover:bg-gray-700 transition-colors cursor-pointer group"
                                    onClick={() => handleTrackClick(track)}
                                >
                                    <div className="flex items-center gap-4">
                                        <div className="w-8 h-8 bg-[đ95c623] rounded-full flex items-center justify-center text-white font-bold text-sm">
                                            {index + 1}
                                        </div>
                                        <div>
                                            <h5 className="font-medium text-white group-hover:text-[var(--primary-500)] transition-colors">
                                                {track.song}
                                            </h5>
                                            <p className="text-sm text-gray-300">
                                                {track.artist} • {track.album}
                                            </p>
                                            <p className="text-xs text-gray-400 mt-1">
                                                {track.reason}
                                            </p>
                                        </div>
                                    </div>
                                    <div className="text-sm text-gray-400">
                                        {track.duration}
                                    </div>
                                </div>
                            ))}
                        </div>
                    </div>
                )}
            </div>

            {/* Share Modal */}
            {showShareModal && playlist && (
                <div className="fixed inset-0 bg-black/50 z-50 flex items-center justify-center p-4">
                    <div className="bg-white rounded-lg p-6 max-w-md w-full max-h-[80vh] overflow-y-auto">
                        <div className="flex items-center justify-between mb-4">
                            <h3 className="text-lg font-semibold text-gray-900 flex items-center gap-2">
                                <Share className="w-5 h-5" />
                                Share "{playlist.name}"
                            </h3>
                            <button
                                onClick={() => setShowShareModal(false)}
                                className="text-gray-400 hover:text-gray-600 transition-colors"
                            >
                                <X className="w-5 h-5" />
                            </button>
                        </div>

                        <div className="space-y-3">
                            <button
                                onClick={copyToClipboard}
                                className="w-full flex items-center gap-3 p-3 text-left hover:bg-gray-50 rounded-lg transition-colors border border-gray-200"
                            >
                                <Copy className="w-5 h-5 text-[var(--primary-500)]" />
                                <div>
                                    <div className="font-medium text-gray-900">
                                        Copy to Clipboard
                                    </div>
                                    <div className="text-sm text-gray-500">
                                        Copy playlist details as text
                                    </div>
                                </div>
                            </button>

                            <button
                                onClick={shareViaEmail}
                                className="w-full flex items-center gap-3 p-3 text-left hover:bg-gray-50 rounded-lg transition-colors border border-gray-200"
                            >
                                <Mail className="w-5 h-5 text-blue-600" />
                                <div>
                                    <div className="font-medium text-gray-900">
                                        Share via Email
                                    </div>
                                    <div className="text-sm text-gray-500">
                                        Send to friends and family
                                    </div>
                                </div>
                            </button>

                            <button
                                onClick={shareViaWhatsApp}
                                className="w-full flex items-center gap-3 p-3 text-left hover:bg-gray-50 rounded-lg transition-colors border border-gray-200"
                            >
                                <MessageCircle className="w-5 h-5 text-green-600" />
                                <div>
                                    <div className="font-medium text-gray-900">
                                        Share on WhatsApp
                                    </div>
                                    <div className="text-sm text-gray-500">
                                        Quick share with contacts
                                    </div>
                                </div>
                            </button>

                            <button
                                onClick={shareViaTwitter}
                                className="w-full flex items-center gap-3 p-3 text-left hover:bg-gray-50 rounded-lg transition-colors border border-gray-200"
                            >
                                <svg
                                    className="w-5 h-5 text-blue-400"
                                    fill="currentColor"
                                    viewBox="0 0 24 24"
                                >
                                    <path d="M23.953 4.57a10 10 0 01-2.825.775 4.958 4.958 0 002.163-2.723c-.951.555-2.005.959-3.127 1.184a4.92 4.92 0 00-8.384 4.482C7.69 8.095 4.067 6.13 1.64 3.162a4.822 4.822 0 00-.666 2.475c0 1.71.87 3.213 2.188 4.096a4.904 4.904 0 01-2.228-.616v.06a4.923 4.923 0 003.946 4.827 4.996 4.996 0 01-2.212.085 4.936 4.936 0 004.604 3.417 9.867 9.867 0 01-6.102 2.105c-.39 0-.779-.023-1.17-.067a13.995 13.995 0 007.557 2.209c9.053 0 13.998-7.496 13.998-13.985 0-.21 0-.42-.015-.63A9.935 9.935 0 0024 4.59z" />
                                </svg>
                                <div>
                                    <div className="font-medium text-gray-900">
                                        Share on Twitter
                                    </div>
                                    <div className="text-sm text-gray-500">
                                        Post to your timeline
                                    </div>
                                </div>
                            </button>
                        </div>

                        <div className="mt-6 pt-4 border-t border-gray-200">
                            <div className="text-sm text-gray-600 text-center">
                                Web Share API:{" "}
                                {navigator.share
                                    ? "✅ Supported"
                                    : "❌ Not supported"}
                            </div>
                        </div>
                    </div>
                </div>
            )}
        </div>
    );
};

export default PlaylistGenerator;
